Repository DO-SOPT-APP6-NAVER-MAP/NAVER-MAP-iOS, pull requests merged in 2023-11, with the labels that each got.

#5 [Add] #1 - 누락 폰트 추가
  NAVER-MAP-iOS.xcodeproj/project.pbxproj
  NAVER-MAP-iOS/Global/Resources/Font/Pretendard-Bold.otf
  NAVER-MAP-iOS/Global/Resources/Font/Pretendard-Medium.otf
  NAVER-MAP-iOS/Global/Resources/Font/Pretendard-Regular.otf
  NAVER-MAP-iOS/Global/Resources/Font/Pretendard-SemiBold.otf
Labels: Setting ⚙️, 다예 🤤

#8 [Feat] 디테일뷰 메인섹션[0] 헤더 구현
  NAVER-MAP-iOS.xcodeproj/project.pbxproj
  NAVER-MAP-iOS/Screen/Detail/DetailViewController.swift
  NAVER-MAP-iOS/Screen/Detail/View/SupplementaryView/DetailMainSectionHeaderView.swift
Labels: Feat 🔧, 영서 😼

#7 [Feat] 지도 뷰 구현
  NAVER-MAP-iOS/Global/Consts/ColorLiterals.swift
  NAVER-MAP-iOS/Global/Consts/ImageLiterals.swift
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/Caption/Contents.json
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/Caption/caption_naverbooking.imageset/Contents.json
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/Caption/caption_naverbooking.imageset/caption_naverbooking_group.png
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/Caption/caption_naverbooking.imageset/caption_naverbooking_group@2x.png
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/Caption/caption_naverbooking.imageset/caption_naverbooking_group@3x.png
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/Caption/caption_naverorder.imageset/Contents.json
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/Caption/caption_naverorder.imageset/caption_naverorder_group.png
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/Caption/caption_naverorder.imageset/caption_naverorder_group@2x.png
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/Caption/caption_naverorder.imageset/caption_naverorder_group@3x.png
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/Caption/caption_naverpay.imageset/Contents.json
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/Caption/caption_naverpay.imageset/caption_naverpay.png
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/Caption/caption_naverpay.imageset/caption_naverpay@2x.png
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/Caption/caption_naverpay.imageset/caption_naverpay@3x.png
  NAVER-MAP-iOS/Screen/SearchResult/SearchResultViewController.swift
Labels: Feat 🔧, 희슬 🤭

#10 [Feat] BottomSheet 뷰 UI 구현
  NAVER-MAP-iOS/Global/Extensions/UILabel+.swift
  NAVER-MAP-iOS/Global/Extensions/UIStackView+.swift
  NAVER-MAP-iOS/Screen/SearchResult/SearchResultViewController.swift
Labels: Feat 🔧, 희슬 🤭

#12 [Feat] #3 - 디테일뷰 Menu 섹션[2] 구현
  NAVER-MAP-iOS.xcodeproj/project.pbxproj
  NAVER-MAP-iOS/Global/Consts/ImageLiterals.swift
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/DetailIcon/icons=ic_to_go.imageset/Contents.json
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/DetailIcon/icons=ic_to_go.imageset/icons=ic_to_go.svg
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/Image/Contents.json
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/Image/img_top_big.imageset/Contents.json
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/Image/img_top_big.imageset/img_top_big.png
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/Image/img_top_big.imageset/img_top_big@2x.png
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/Image/img_top_big.imageset/img_top_big@3x.png
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/Image/img_top_small_1.imageset/Contents.json
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/Image/img_top_small_1.imageset/img_top_small_1.png
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/Image/img_top_small_1.imageset/img_top_small_1@2x.png
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/Image/img_top_small_1.imageset/img_top_small_1@3x.png
  NAVER-MAP-iOS/Screen/Detail/Data/DetailAppData.swift
  NAVER-MAP-iOS/Screen/Detail/DetailViewController.swift
  NAVER-MAP-iOS/Screen/Detail/View/Cell/MenuCollectionViewCell.swift
  NAVER-MAP-iOS/Screen/Detail/View/Cell/VisitorReviewCollectionViewCell.swift
  NAVER-MAP-iOS/Screen/Detail/View/SupplementaryView/DescriptionSectionHeaderView.swift
  NAVER-MAP-iOS/Screen/Detail/View/SupplementaryView/DetailMainSectionHeaderView.swift
  NAVER-MAP-iOS/Screen/Detail/View/SupplementaryView/MenuSectionFooterView.swift
  NAVER-MAP-iOS/Screen/Detail/View/SupplementaryView/MenuSectionHeaderView.swift
  NAVER-MAP-iOS/Screen/SearchResult/SearchResultViewController.swift
Labels: Feat 🔧, 영서 😼

#15 [Feat] #13 - 장소 검색 UI 구현
  NAVER-MAP-iOS.xcodeproj/project.pbxproj
  NAVER-MAP-iOS/Screen/MainSearch/MainSearchViewController.swift
  NAVER-MAP-iOS/Screen/MainSearch/Model/MainSearchLocationModel.swift
  NAVER-MAP-iOS/Screen/MainSearch/View/Cell/SearchRecommendCollectionViewCell.swift
  NAVER-MAP-iOS/Screen/MainSearch/View/Cell/SearchResultTableViewCell.swift
  NAVER-MAP-iOS/Screen/MainSearch/View/EmptySearchView.swift
  NAVER-MAP-iOS/Screen/MainSearch/View/MainSearchRootView.swift
  NAVER-MAP-iOS/Screen/MainSearch/ViewController/MainSearchViewController.swift
Labels: 다예 🤤, Feat 🔧

#16 [Feat] #3 - 디테일뷰 Visitor Review 섹션[3] 구현
  NAVER-MAP-iOS.xcodeproj/project.pbxproj
  NAVER-MAP-iOS/Global/Consts/ImageLiterals.swift
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/DetailIcon/bar_review1.imageset/Contents.json
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/DetailIcon/bar_review1.imageset/bar_review1.png
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/DetailIcon/bar_review1.imageset/bar_review1@2x.png
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/DetailIcon/bar_review1.imageset/bar_review1@3x.png
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/DetailIcon/bar_review2.imageset/Contents.json
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/DetailIcon/bar_review2.imageset/bar_review2.png
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/DetailIcon/bar_review2.imageset/bar_review2@2x.png
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/DetailIcon/bar_review2.imageset/bar_review2@3x.png
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/DetailIcon/bar_review3.imageset/Contents.json
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/DetailIcon/bar_review3.imageset/bar_review3.png
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/DetailIcon/bar_review3.imageset/bar_review3@2x.png
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/DetailIcon/bar_review3.imageset/bar_review3@3x.png
  NAVER-MAP-iOS/Screen/Detail/Data/DetailMenuData.swift
  NAVER-MAP-iOS/Screen/Detail/Data/DetailVisitorReviewData.swift
  NAVER-MAP-iOS/Screen/Detail/DetailViewController.swift
  NAVER-MAP-iOS/Screen/Detail/View/Cell/MenuCollectionViewCell.swift
  NAVER-MAP-iOS/Screen/Detail/View/SupplementaryView/MenuSectionHeaderView.swift
  NAVER-MAP-iOS/Screen/Detail/View/SupplementaryView/SectionFooterView.swift
  NAVER-MAP-iOS/Screen/Detail/View/SupplementaryView/VisitorSectionHeaderView.swift
Labels: Feat 🔧, 영서 😼

#14 [Feat] 검색 결과 뷰 세부 기능 구현
  NAVER-MAP-iOS.xcodeproj/project.pbxproj
  NAVER-MAP-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  NAVER-MAP-iOS/Global/Extensions/FloatingPanelController+.swift
  NAVER-MAP-iOS/Global/Extensions/UIImageView+.swift
  NAVER-MAP-iOS/Global/Extensions/UILabel+.swift
  NAVER-MAP-iOS/Global/Extensions/UIStackView+.swift
  NAVER-MAP-iOS/Screen/SearchResult/DetailLocationView.swift
  NAVER-MAP-iOS/Screen/SearchResult/DetailLocationViewController.swift
  NAVER-MAP-iOS/Screen/SearchResult/MyFloatingPanelLayout.swift
  NAVER-MAP-iOS/Screen/SearchResult/SearchResultViewController.swift
Labels: Feat 🔧, 희슬 🤭

#18 [Feat] #3 블로그 리뷰 섹션[4], 관련 링크 섹션[5] 구현
  NAVER-MAP-iOS.xcodeproj/project.pbxproj
  NAVER-MAP-iOS/Global/Consts/ImageLiterals.swift
  NAVER-MAP-iOS/Global/Extensions/UILabel+.swift
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/DetailIcon/Naver_Logotype_1.imageset/Contents.json
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/DetailIcon/Naver_Logotype_1.imageset/Naver_Logotype_1.svg
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/NormalIcon/ic_arrow_up.imageset/Contents.json
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/NormalIcon/ic_arrow_up.imageset/ic_arrow_up.svg
  NAVER-MAP-iOS/Screen/Detail/Data/DetailBlogData.swift
  NAVER-MAP-iOS/Screen/Detail/DetailViewController.swift
  NAVER-MAP-iOS/Screen/Detail/View/Cell/BlogReviewCollectionViewCell.swift
  NAVER-MAP-iOS/Screen/Detail/View/Cell/VisitorReviewCollectionViewCell.swift
  NAVER-MAP-iOS/Screen/Detail/View/SupplementaryView/BlogSectionHeaderView.swift
  NAVER-MAP-iOS/Screen/Detail/View/SupplementaryView/LinksSectionHeaderView.swift
  NAVER-MAP-iOS/Screen/Detail/View/SupplementaryView/VisitorSectionHeaderView.swift
Labels: Feat 🔧, 영서 😼

#23 [Fix] #22 - UILabel 익스텐션 수정
  NAVER-MAP-iOS/Global/Extensions/UILabel+.swift
Labels: 영서 😼, Fix 🛠️

#20 [Feat] #17 - 길찾기 UI 구현
  NAVER-MAP-iOS.xcodeproj/project.pbxproj
  NAVER-MAP-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  NAVER-MAP-iOS/Global/Consts/ImageLiterals.swift
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/FindRouteIcon/btn_bus_info_ios.imageset/Contents.json
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/FindRouteIcon/btn_bus_info_ios.imageset/btn_bus_info_ios.svg
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/FindRouteIcon/ic_btn_bus_white.imageset/Contents.json
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/FindRouteIcon/ic_btn_bus_white.imageset/ic_btn_bus_white.svg
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/FindRouteIcon/ic_dropdown_circle.imageset/Contents.json
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/FindRouteIcon/ic_dropdown_circle.imageset/ic_dropdown_circle.svg
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/FindRouteIcon/tap_choice_transport_ios.imageset/Contents.json
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/FindRouteIcon/tap_choice_transport_ios.imageset/tap_choice_transport_ios (1).png
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/FindRouteIcon/tap_choice_transport_ios.imageset/tap_choice_transport_ios (2).png
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/FindRouteIcon/tap_choice_transport_ios.imageset/tap_choice_transport_ios.png
  NAVER-MAP-iOS/Screen/FindingRoute/FindingRouteViewController.swift
  NAVER-MAP-iOS/Screen/FindingRoute/Model/FindingRouteModel.swift
  NAVER-MAP-iOS/Screen/FindingRoute/View/Cell/FindingRouteCollectionViewCell.swift
  NAVER-MAP-iOS/Screen/FindingRoute/View/FindingRouteRootView.swift
  NAVER-MAP-iOS/Screen/FindingRoute/ViewController/FindingRouteViewController.swift
Labels: 다예 🤤, Feat 🔧

#24 [Feat] #19 - 버튼 탭 시 스크롤 구현
  NAVER-MAP-iOS.xcodeproj/project.pbxproj
  NAVER-MAP-iOS/Screen/Detail/Data/LocationModel.swift
  NAVER-MAP-iOS/Screen/Detail/DetailViewController.swift
  NAVER-MAP-iOS/Screen/Detail/View/SupplementaryView/BlogSectionHeaderView.swift
  NAVER-MAP-iOS/Screen/Detail/View/SupplementaryView/DetailMainSectionHeaderView.swift
  NAVER-MAP-iOS/Screen/Detail/View/SupplementaryView/LinksSectionHeaderView.swift
  NAVER-MAP-iOS/Screen/Detail/View/SupplementaryView/VisitorSectionHeaderView.swift
Labels: Feat 🔧, 영서 😼

#28 [Setting] #17 - 네트워크 세팅
  NAVER-MAP-iOS.xcodeproj/project.pbxproj
  NAVER-MAP-iOS/Global/Supporting Files/Config.swift
  NAVER-MAP-iOS/Global/Supporting Files/Info.plist
  NAVER-MAP-iOS/Network/Base/BaseService.swift
  NAVER-MAP-iOS/Network/Base/BaseTargetType.swift
  NAVER-MAP-iOS/Network/Base/MoyaPlugin.swift
  NAVER-MAP-iOS/Network/Base/NetworkResult.swift
  NAVER-MAP-iOS/Network/Base/NetworkService.swift
  NAVER-MAP-iOS/Network/Place/DTO/GetPlaceResultDetailResponseDTO.swift
  NAVER-MAP-iOS/Network/Place/DTO/GetPlaceResultSimpleResponseDTO.swift
  NAVER-MAP-iOS/Network/Place/DTO/GetPlaceRouteResponseDTO.swift
  NAVER-MAP-iOS/Network/Place/DTO/GetPlaceSearchResponseDTO.swift
  NAVER-MAP-iOS/Network/Place/PlaceAPI.swift
  NAVER-MAP-iOS/Network/Place/PlaceAPIService.swift
  NAVER-MAP-iOS/Screen/ViewController.swift
Labels: Setting ⚙️, 다예 🤤

#31 [Feat] #27 - 스크롤에 따른 헤더 구현
  NAVER-MAP-iOS.xcodeproj/project.pbxproj
  NAVER-MAP-iOS/Global/Consts/ImageLiterals.swift
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/DetailIcon/ic_multiply.imageset/Contents.json
  NAVER-MAP-iOS/Global/Resources/Assets.xcassets/DetailIcon/ic_multiply.imageset/ic_multiply.svg
  NAVER-MAP-iOS/Screen/Detail/DetailViewController.swift
  NAVER-MAP-iOS/Screen/Detail/View/DescriptionTopHeaderView.swift
  NAVER-MAP-iOS/Screen/Detail/View/DetailTopHeaderView.swift
  NAVER-MAP-iOS/Screen/Detail/View/SupplementaryView/DescriptionSectionHeaderView.swift
Labels: Feat 🔧, 영서 😼
