Repository DO-SOPT-APP6-NAVER-MAP/NAVER-MAP-iOS, pull requests merged in 2023-12, with the labels that each got.

#34 [Feat] #29 - 장소 검색 서버 통신
  NAVER-MAP-iOS/Screen/MainSearch/Model/MainSearchLocationModel.swift
  NAVER-MAP-iOS/Screen/MainSearch/ViewController/MainSearchViewController.swift
Labels: 다예 🤤, Feat 🔧, Network 🌏

#35 [Feat] #33 - 길찾기 서버 통신
  NAVER-MAP-iOS/Screen/FindingRoute/View/FindingRouteRootView.swift
  NAVER-MAP-iOS/Screen/FindingRoute/ViewController/FindingRouteViewController.swift
Labels: 다예 🤤, Feat 🔧, Network 🌏

#36 [Feat] #30 서치 결과 서버 통신
  NAVER-MAP-iOS/Screen/SearchResult/DetailLocationViewController.swift
  NAVER-MAP-iOS/Screen/SearchResult/SearchResultViewController.swift
Labels: Feat 🔧, 희슬 🤭, Network 🌏

#39 [Feat] #37 - 지도 서버 통신
  NAVER-MAP-iOS.xcodeproj/project.pbxproj
  NAVER-MAP-iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  NAVER-MAP-iOS/Application/AppDelegate.swift
  NAVER-MAP-iOS/Global/Supporting Files/Config.swift
  NAVER-MAP-iOS/Global/Supporting Files/Info.plist
  NAVER-MAP-iOS/Network/Map/DTO/GetLocationDTO.swift
  NAVER-MAP-iOS/Network/Map/MapAPIService.swift
  NAVER-MAP-iOS/Screen/SearchResult/DetailLocationView.swift
  NAVER-MAP-iOS/Screen/SearchResult/DetailLocationViewController.swift
  NAVER-MAP-iOS/Screen/SearchResult/SearchResultViewController.swift
  Podfile
  Podfile.lock
Labels: Feat 🔧, 희슬 🤭, Network 🌏

#41 [Feat] #40 - 페이지 연결
  NAVER-MAP-iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  NAVER-MAP-iOS/Application/SceneDelegate.swift
  NAVER-MAP-iOS/Global/Extensions/FloatingPanelController+.swift
  NAVER-MAP-iOS/Network/Place/DTO/GetPlaceResultSimpleResponseDTO.swift
  NAVER-MAP-iOS/Screen/Detail/DetailViewController.swift
  NAVER-MAP-iOS/Screen/Detail/View/SupplementaryView/DetailMainSectionHeaderView.swift
  NAVER-MAP-iOS/Screen/MainSearch/ViewController/MainSearchViewController.swift
  NAVER-MAP-iOS/Screen/SearchResult/DetailLocationView.swift
  NAVER-MAP-iOS/Screen/SearchResult/DetailLocationViewController.swift
  NAVER-MAP-iOS/Screen/SearchResult/MyFloatingPanelLayout.swift
  NAVER-MAP-iOS/Screen/SearchResult/SearchResultViewController.swift
Labels: Feat 🔧, 희슬 🤭

#45 [Refactor] #44 - 검색 뷰 리펙토링
  NAVER-MAP-iOS.xcodeproj/project.pbxproj
  NAVER-MAP-iOS/Global/Components/View/EmptySearchView.swift
  NAVER-MAP-iOS/Screen/MainSearch/View/MainSearchRootView.swift
  NAVER-MAP-iOS/Screen/MainSearch/View/MainSearchViewController.swift
  NAVER-MAP-iOS/Screen/MainSearch/ViewController/MainSearchViewController.swift
  NAVER-MAP-iOS/Screen/MainSearch/ViewModel/MainSearchViewModel.swift
Labels: Refactor🔧, 다예 🤤
